### ISSUE TITLE
(Not an issue) help -> Commands listing Idea

### ISSUE THREAD

**Issue by WatchaGames** [yasirkula/UnityIngameDebugConsole#24]
Hi Yasir,
First of all THANKS for all your great assets. SUPER USEFUL.

Today was digging into using console commands.
Everything works well so far.

Small hiccup / user (programmer) experience I had:

I added several commands and was puzzled because when typing help I would only see the first one...
After digging into the code I understood that I have to click on the line in the console to expand it and see all the commands.

UX wise it can lead to think that it does not work...

Ideas:
- Maybe for this particular command print only the commands directly to the ingame console instead of going through the unityconsole which adds a lot of infos which are not super useful for users (for example my artists/designers).
- Print one command per line (might scroll too much for many commands).

Anyway for now as I did not want to modify you code I added a fake first command which is called "CLICK_HERE_TO_SEE_COMMANDS" ;-)

Nicolas

**Comment by yasirkula** [comment]
Nice workaround there 😄

Your first idea sounds nice but it doesn't have a high priority because it affects only the developers, not end users. In release builds, Unity doesn't provide a stacktrace to logs anyways (unless they've changed it) so the stacktrace is only visible to the developers.

I think a better alternative to your second idea would be to automatically expand the help log. I'll keep it in mind and keep this Issue open in the meantime.

Thank you for the feedback!
