### ISSUE TITLE
"Hidden" F12 mode

### ISSUE THREAD

**Issue by klootas** [yasirkula/UnityIngameDebugConsole#27]
Currently (as I understand it), the console must be visible in order for logs to be collected. I would love to have a built-in "hidden" mode where the console is logging messages but remained hidden until the user presses a key to show it (much like the F12 tools in your browser).

This way games can be released having the console active but invisible and when people have issues you tell them to press F12 and send you the console output to go with their bug report.

Thanks for this great asset!

**Comment by yasirkula** [comment]
You can put an IngameDebugConsole instance at the first scene of your project with the following settings:

![settings](https://user-images.githubusercontent.com/10211608/92462055-a3b20300-f1d2-11ea-9811-e00c0bbbaf24.png)

**Comment by klootas** [comment]
Thanks, that's almost what I wanted but I was thinking in combination with pop-up mode, one button to toggle between minimized, pop-up, full console. Or one button to toggle between popup/console and one to toggle minimized on/off.

**Comment by yasirkula** [comment]
You can use the **ShowLogWindow** and **ShowPopup** functions but you'll still need to modify _DebugLogManager.cs_ slightly because when _enablePopup_ is disabled at startup, `popupManager.gameObject.SetActive( enablePopup );` will deactivate the popup in _Start_ function. You'll need to reactivate this GameObject when you want to start showing the popup.

I guess a few lines of code modification should be fine, it is memorable and I don't really update the plugin that often.

**Comment by klootas** [comment]
Sure thing, thanks!
