### ISSUE TITLE
Feature Request: Set a global font for the console in IngameDebugConsole -prefab

### ISSUE THREAD

**Issue by Efmi** [yasirkula/UnityIngameDebugConsole#37]
I like to have my console using the same font as the rest of the game for the aesthetics, and every time I upgrade, I need to reset the font for all the plugins prefabs. Maybe there could be a field in IngameDebugConsole -prefab where you are able to set the font for the entire console?

**Comment by yasirkula** [comment]
I hear you. I'm not too eager to resolve this problem because it'll be a hassle to resolve it. I might do so in the future, though.

Most of the time, I don't touch the prefabs. So to ease this process, before updating the plugin, I'd recommend you to check out the latest commit(s) on GitHub and see if any of the prefabs have changed. If not, simply don't overwrite those prefabs while updating the plugin.
