### ISSUE TITLE
if command input field ignore case may be more easy to use ☺

### ISSUE THREAD

**Issue by so-sos-so** [yasirkula/UnityIngameDebugConsole#38]

**Comment by yasirkula** [comment]
I agree, it can be useful.

**Comment by so-sos-so** [comment]
emm .. if pop command tips can click ,  it will be better , when use phone with low solution , hard to see tips, and no tab button like computer

**Comment by yasirkula** [comment]
Unfortunately, I couldn't implement the second feature because whenever we tap somewhere other than the command input field, command input field immediately loses focus. This would result in the following weird scenario:

- A command is partially typed
- User attempts to click a command in the list
- The moment he/she taps the screen, command input field loses focus
- As the command input field loses focus, on screen keyboard is hidden
- When the user releases their finger from the screen, the clicked command is automatically entered to command input field and command input field regains focus
- As the command input field regains focus from scratch, the whole text inside it will be selected, the cursor will snap to the end and the on screen keyboard will appear again (milliseconds after it disappears, causing an annoying UX)
