### ISSUE TITLE
Cosmetic issues

### ISSUE THREAD

**Issue by XeonG** [yasirkula/UnityIngameDebugConsole#46]
So when you click on a log to expand it the LogText moves up slightly in height position by around 1px, just a bit annoying, because you notice the first text line is the same just moving upwards when the lines below are revealed, seems to be bit of a harder issue to fix in code, than the my other minor niggle which I've fixed myself in the DebuglogItem prefab with the LogType anchor position that gets moved to the middle on expansion, instead of just remaining at the top in the same position on log item expansion.

**Comment by yasirkula** [comment]
You can modify DebugLogItem prefab and set LogText child object's vertical alignment to Top. I'm not planning to implement this myself because when Text is top-aligned, its RectTransform's Top offset value must be adjusted by the user if they decide to change DebugLogItem prefab's height. It isn't needed when Text is middle-aligned.

**Comment by XeonG** [comment]
I found a better solution without changing any of the pivot stuff was to just change the LogText Text components vertical alignment to Top.... no other changes and it works much better now, no position shifting when expanding logs :)

**Comment by yasirkula** [comment]
I also said changing vertical alignment to Top. But if you don't change RectTransform's Top offset afterwards, text will be snapped to the top edge of the log entry, it looks very ugly.
