### ISSUE TITLE
Make copy to clipboard a separate package

### ISSUE THREAD

**Issue by achimmihca** [yasirkula/UnityIngameDebugConsole#80]
I noticed that this package contains code to copy a string to the system clipboard, including for Android and iOS via native code. Thanks!

IMHO this is pretty useful and would make for a separate package.

**Comment by yasirkula** [comment]
There's no longer a need for it since `GUIUtility.systemCopyBuffer` works for 2018.1 and newer and is actually what this plugin also uses when applicable: https://github.com/yasirkula/UnityIngameDebugConsole/blob/2ee62e21eded65257454d14d545f5db7484743b0/Plugins/IngameDebugConsole/Scripts/DebugLogItem.cs#L235-L237

**Comment by achimmihca** [comment]
Ahh, thanks! I was not aware of `GUIUtility.systemCopyBuffer`
