### ISSUE TITLE
Can log entries always be expanded?

### ISSUE THREAD

**Issue by XeonG** [yasirkula/UnityIngameDebugConsole#86]
would be nicer.. just wondering I'm guess the fixed un expanded size for performance reasons?

**Comment by yasirkula** [comment]
You're right, a major benefit of the current approach is performance. Since the plugin uses recycled list view, it's much faster to assume a specific height for all log entries while reusing the log entry GameObjects. Otherwise, all log entries' sizes must be calculated separately and all of them must be summed up one by one while scrolling to correctly reuse the log entries.

I'm not planning add this feature myself but if you decide to do so, you'll mostly be modifying DebugLogRecycledListView.
